# docker-compose.yml
version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017

  app:
    build: ./
    image: izafar/node-api-seed:latest
    container_name: node-api-seed
    env_file: .env
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - ${PORT}:${PORT}
    